# Generated by Django 6.0.3 on 2026-04-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
